version: 2

updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:00'
      timezone: Asia/Kolkata
    groups:
      bun-dependencies:
        patterns:
          - '*'
    labels:
      - dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: '04:00'
      timezone: Asia/Kolkata
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: '04:30'
      timezone: Asia/Kolkata
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: '04:00'
      timezone: Asia/Kolkata
    labels:
      - dependencies
      - github-actions
